import { readFile } from "node:fs/promises";
import path from "node:path";
import { PDFDocument, rgb } from "pdf-lib";
import { parse as parseFont, type Font } from "opentype.js";
import sharp from "sharp";

// ---------------------------------------------------------------------------
// Print-vendor ("Ron") export: a single VECTOR sticker template (PDF) plus a
// CSV of per-sticker data, for variable-data printing.
//
// Ron's spec:
//   - true vector, any format (PDF here), with FONTS OUTLINED (converted to
//     paths) so no font files are needed on his end
//   - BLEED + CROP MARKS so trimming/spacing is exact
//   - QR codes are generated by Ron's shop FROM THE CSV as plain square QR, so
//     the template leaves a labelled QR placeholder box rather than embedding
//     any QR image
//   - every element that varies per sticker is its own CSV column
//
// For a TagBatch the only things that vary per sticker are the tag `code` and
// its `qr_url` — tags print as blanks and are linked to equipment later — so
// the batch's restaurant logo + name are baked into the template and the CSV
// carries `code` + `qr_url`. Ron merges one template × N rows.
// ---------------------------------------------------------------------------

const PT_PER_IN = 72;
const inPt = (inches: number) => inches * PT_PER_IN;

// Trim + bleed. Trim matches the raster sticker (see stickerExport.ts).
const TRIM_W_IN = 2.5;
const TRIM_H_IN = 3.4;
const BLEED_IN = 0.125;

// Crop marks live in the bleed margin: a small gap off the trim edge, then a
// short line reaching the page edge. gap + len == bleed so marks touch the edge.
const CROP_GAP_IN = 0.04;
const CROP_LEN_IN = BLEED_IN - CROP_GAP_IN;

// Content stack (top → bottom), mirroring the raster layout's proportions but
// with a touch more breathing room since this is the print master.
const LOGO_BOX_W_IN = 2.1;
const LOGO_BOX_H_IN = 1.18;
const QR_SIZE_IN = 1.2;
const GAP_LOGO_QR_IN = 0.1;
const GAP_QR_CODE_IN = 0.11;
const GAP_CODE_NAME_IN = 0.07;
const GAP_NAME_SCAN_IN = 0.05;

const CODE_FONT_PT = 12;
const NAME_FONT_PT = 9;
const SCAN_FONT_PT = 9.5;
const QR_LABEL_FONT_PT = 7.5;

const BLACK = rgb(0, 0, 0);
const GUIDE = rgb(0.6, 0.6, 0.6); // placeholders Ron replaces (sample code, QR label)

// A visible sample so Ron sees the exact size/position/case of the tag code.
// The README makes clear this is replaced per row from the CSV `code` column.
const SAMPLE_CODE = "A1B2C3D4";

let cachedFont: Font | null = null;
async function loadOutlineFont(): Promise<Font> {
  if (cachedFont) return cachedFont;
  const buf = await readFile(
    path.join(process.cwd(), "public", "fonts", "BarlowCondensed-Bold.ttf")
  );
  // opentype.parse wants a standalone ArrayBuffer, not a Node Buffer view.
  const ab = buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength);
  cachedFont = parseFont(ab);
  return cachedFont;
}

// Same two-shape logo loader as stickerExport.ts (root-relative /public path
// for built-in logos, absolute URL for admin-uploaded Blob logos).
async function loadLogo(logoUrl: string): Promise<Buffer> {
  if (/^https?:\/\//i.test(logoUrl)) {
    const res = await fetch(logoUrl);
    if (!res.ok) throw new Error(`Could not load print logo (${res.status}): ${logoUrl}`);
    return Buffer.from(await res.arrayBuffer());
  }
  return readFile(path.join(process.cwd(), "public", logoUrl.replace(/^\//, "")));
}

type LineMetrics = { d: string; width: number };

// One line of text, outlined to a filled vector path via opentype. Coordinates
// come back in points with the baseline at y=0 (ascenders negative-y), which is
// exactly what pdf-lib's drawSvgPath consumes.
function outlineLine(font: Font, text: string, fontSizePt: number): LineMetrics {
  const p = font.getPath(text, 0, 0, fontSizePt);
  return { d: p.toPathData(2), width: font.getAdvanceWidth(text, fontSizePt) };
}

export async function renderStickerTemplatePdf(opts: {
  restaurantName: string;
  logoUrl: string;
}): Promise<Uint8Array> {
  const { restaurantName, logoUrl } = opts;
  const font = await loadOutlineFont();

  const pageW = inPt(TRIM_W_IN + 2 * BLEED_IN);
  const pageH = inPt(TRIM_H_IN + 2 * BLEED_IN);
  const bleed = inPt(BLEED_IN);
  const trimW = inPt(TRIM_W_IN);
  const trimH = inPt(TRIM_H_IN);

  const doc = await PDFDocument.create();
  const page = doc.addPage([pageW, pageH]);

  // Trim box edges in page coords (origin bottom-left, y up).
  const trimLeft = bleed;
  const trimRight = bleed + trimW;
  const trimBottom = bleed;
  const trimTop = bleed + trimH;

  // Logo, grayscaled to match the app's black & white tag printing.
  const grayLogo = await sharp(await loadLogo(logoUrl)).grayscale().png().toBuffer();
  const logoMeta = await sharp(grayLogo).metadata();
  const logoNativeW = logoMeta.width ?? 1;
  const logoNativeH = logoMeta.height ?? 1;
  const embeddedLogo = await doc.embedPng(grayLogo);

  const boxW = inPt(LOGO_BOX_W_IN);
  const boxH = inPt(LOGO_BOX_H_IN);
  const logoFit = Math.min(boxW / logoNativeW, boxH / logoNativeH);
  const logoW = logoNativeW * logoFit;
  const logoH = logoNativeH * logoFit;

  const qr = inPt(QR_SIZE_IN);

  // Line-box heights (~1.3× font size) used only for vertical stacking.
  const codeH = CODE_FONT_PT * 1.3;
  const nameH = NAME_FONT_PT * 1.3;
  const scanH = SCAN_FONT_PT * 1.3;

  const contentH =
    boxH +
    inPt(GAP_LOGO_QR_IN) +
    qr +
    inPt(GAP_QR_CODE_IN) +
    codeH +
    inPt(GAP_CODE_NAME_IN) +
    nameH +
    inPt(GAP_NAME_SCAN_IN) +
    scanH;

  // Work in "distance from the top of the page" (dTop), then convert to pdf-lib
  // y-up page coords at the moment of drawing.
  let dTop = bleed + Math.max(0, (trimH - contentH) / 2);
  const centerX = pageW / 2;

  const putLine = (line: LineMetrics, fontSizePt: number, lineBoxH: number, color = BLACK) => {
    // Sit the baseline near the bottom of the line box, leaving descender room.
    const baselineFromTop = dTop + fontSizePt;
    const baselineY = pageH - baselineFromTop;
    page.drawSvgPath(line.d, {
      x: centerX - line.width / 2,
      y: baselineY,
      color,
      borderWidth: 0,
    });
    dTop += lineBoxH;
  };

  // --- Logo ---
  page.drawImage(embeddedLogo, {
    x: centerX - logoW / 2,
    y: pageH - (dTop + (boxH - logoH) / 2 + logoH),
    width: logoW,
    height: logoH,
  });
  dTop += boxH + inPt(GAP_LOGO_QR_IN);

  // --- QR placeholder box (Ron drops a square QR here, generated from qr_url) ---
  const qrX = centerX - qr / 2;
  const qrTopFromTop = dTop;
  const qrY = pageH - (qrTopFromTop + qr);
  page.drawRectangle({
    x: qrX,
    y: qrY,
    width: qr,
    height: qr,
    borderColor: GUIDE,
    borderWidth: 0.75,
  });
  const qrLabel = outlineLine(font, "QR CODE", QR_LABEL_FONT_PT);
  page.drawSvgPath(qrLabel.d, {
    x: centerX - qrLabel.width / 2,
    y: qrY + qr / 2 + QR_LABEL_FONT_PT / 2,
    color: GUIDE,
    borderWidth: 0,
  });
  dTop += qr + inPt(GAP_QR_CODE_IN);

  // --- Tag code (sample; Ron replaces per row from CSV `code`) ---
  putLine(outlineLine(font, SAMPLE_CODE, CODE_FONT_PT), CODE_FONT_PT, codeH, GUIDE);
  dTop += inPt(GAP_CODE_NAME_IN);

  // --- Restaurant name (baked in, constant for the batch) ---
  putLine(outlineLine(font, restaurantName.toUpperCase(), NAME_FONT_PT), NAME_FONT_PT, nameH);
  dTop += inPt(GAP_NAME_SCAN_IN);

  // --- SCAN ME ---
  putLine(outlineLine(font, "SCAN ME", SCAN_FONT_PT), SCAN_FONT_PT, scanH);

  // --- Crop marks at the four trim corners ---
  const gap = inPt(CROP_GAP_IN);
  const len = inPt(CROP_LEN_IN);
  const mark = (start: [number, number], end: [number, number]) =>
    page.drawLine({ start: { x: start[0], y: start[1] }, end: { x: end[0], y: end[1] }, thickness: 0.75, color: BLACK });
  // top-left
  mark([trimLeft, trimTop + gap], [trimLeft, trimTop + gap + len]);
  mark([trimLeft - gap, trimTop], [trimLeft - gap - len, trimTop]);
  // top-right
  mark([trimRight, trimTop + gap], [trimRight, trimTop + gap + len]);
  mark([trimRight + gap, trimTop], [trimRight + gap + len, trimTop]);
  // bottom-left
  mark([trimLeft, trimBottom - gap], [trimLeft, trimBottom - gap - len]);
  mark([trimLeft - gap, trimBottom], [trimLeft - gap - len, trimBottom]);
  // bottom-right
  mark([trimRight, trimBottom - gap], [trimRight, trimBottom - gap - len]);
  mark([trimRight + gap, trimBottom], [trimRight + gap + len, trimBottom]);

  return doc.save();
}

// One row per non-voided tag. `code` + `qr_url` are the only variable fields;
// Ron generates a plain square QR from `qr_url`.
export function buildStickerCsv(tags: { code: string }[], baseUrl: string): string {
  const esc = (v: string) => (/[",\n]/.test(v) ? `"${v.replace(/"/g, '""')}"` : v);
  const rows = [["code", "qr_url"].join(",")];
  for (const t of tags) {
    rows.push([esc(t.code), esc(`${baseUrl}/t/${t.code}`)].join(","));
  }
  return rows.join("\r\n") + "\r\n";
}

export function buildPrinterReadme(opts: {
  restaurantName: string;
  batchNumber: number;
  tagCount: number;
}): string {
  const { restaurantName, batchNumber, tagCount } = opts;
  return [
    `PRINT-VENDOR FILES — Batch ${batchNumber} (${restaurantName})`,
    `${tagCount} stickers`,
    ``,
    `FILES`,
    `  sticker-template.pdf   One master sticker, true vector, fonts outlined.`,
    `  stickers.csv           One row per sticker (the variable data).`,
    ``,
    `SIZE`,
    `  Trim:  ${TRIM_W_IN}in x ${TRIM_H_IN}in`,
    `  Bleed: ${BLEED_IN}in on all sides (page is ${TRIM_W_IN + 2 * BLEED_IN}in x ${TRIM_H_IN + 2 * BLEED_IN}in)`,
    `  Crop marks are included at the trim corners.`,
    ``,
    `VARIABLE DATA (merge one row per sticker)`,
    `  code    -> the tag code text (replaces the grey sample "${SAMPLE_CODE}").`,
    `  qr_url  -> generate a PLAIN SQUARE QR code from this URL and place it in`,
    `             the "QR CODE" box on the template. No styling / rounded modules.`,
    ``,
    `The grey "QR CODE" box outline and the grey sample code are PLACEMENT GUIDES`,
    `— replace them with the real QR + code; they are not meant to print.`,
    ``,
    `Everything else on the template (logo, restaurant name, "SCAN ME") is the`,
    `same on every sticker in this batch. Print black on white.`,
    ``,
  ].join("\n");
}
